// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPH6yVK40tlAYO-RjvcBXytK188Gtd0Sw',
    appId: '1:717902373816:android:3e59190165bc71d2d8654d',
    messagingSenderId: '717902373816',
    projectId: 'my-grow-project-6c5a6',
    databaseURL: 'https://my-grow-project-6c5a6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-grow-project-6c5a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8vRgFj4OS5SWONhZsG0vcRcXKepplxzE',
    appId: '1:717902373816:ios:0e6d6b7f3cae326cd8654d',
    messagingSenderId: '717902373816',
    projectId: 'my-grow-project-6c5a6',
    databaseURL: 'https://my-grow-project-6c5a6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-grow-project-6c5a6.appspot.com',
    iosBundleId: 'com.example.mygrowAdmin',
  );
}
